/* Character classes for tokenizing
**
** In the sqlite3GetToken() function, a switch() on aiClass[c] is implemented
** using a lookup table, whereas a switch() directly on c uses a binary search.
** The lookup table is much faster.  To maximize speed, and to ensure that
** a lookup table is used, all of the classes need to be small integers and
** all of them need to be used within the switch.
*/
const CC_X: u8 = 0; /* The letter 'x', or start of BLOB literal */
const CC_KYWD0: u8 = 1; /* First letter of a keyword */
const CC_KYWD: u8 = 2; /* Alphabetics or '_'.  Usable in a keyword */
const CC_DIGIT: u8 = 3; /* Digits */
const CC_DOLLAR: u8 = 4; /* '$' */
const CC_VARALPHA: u8 = 5; /* '@', '#', ':'.  Alphabetic SQL variables */
const CC_VARNUM: u8 = 6; /* '?'.  Numeric SQL variables */
const CC_SPACE: u8 = 7; /* Space characters */
const CC_QUOTE: u8 = 8; /* '"', '\'', or '`'.  String literals, quoted ids */
const CC_QUOTE2: u8 = 9; /* '['.   [...] style quoted ids */
const CC_PIPE: u8 = 10; /* '|'.   Bitwise OR or concatenate */
const CC_MINUS: u8 = 11; /* '-'.  Minus or SQL-style comment */
const CC_LT: u8 = 12; /* '<'.  Part of < or <= or <> */
const CC_GT: u8 = 13; /* '>'.  Part of > or >= */
const CC_EQ: u8 = 14; /* '='.  Part of = or == */
const CC_BANG: u8 = 15; /* '!'.  Part of != */
const CC_SLASH: u8 = 16; /* '/'.  / or c-style comment */
const CC_LP: u8 = 17; /* '(' */
const CC_RP: u8 = 18; /* ')' */
const CC_SEMI: u8 = 19; /* ';' */
const CC_PLUS: u8 = 20; /* '+' */
const CC_STAR: u8 = 21; /* '*' */
const CC_PERCENT: u8 = 22; /* '%' */
const CC_COMMA: u8 = 23; /* ',' */
const CC_AND: u8 = 24; /* '&' */
const CC_TILDA: u8 = 25; /* '~' */
const CC_DOT: u8 = 26; /* '.' */
const CC_ID: u8 = 27; /* unicode characters usable in IDs */
const CC_ILLEGAL: u8 = 28; /* Illegal character */
const CC_NUL: u8 = 29; /* 0x00 */
const CC_BOM: u8 = 30; /* First byte of UTF8 BOM:  0xEF 0xBB 0xBF */

#[rustfmt::skip]
static  aiClass: &[u8] = &[
/*         x0  x1  x2  x3  x4  x5  x6  x7  x8  x9  xa  xb  xc  xd  xe  xf */
/* 0x */   29, 28, 28, 28, 28, 28, 28, 28, 28,  7,  7, 28,  7,  7, 28, 28,
/* 1x */   28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
/* 2x */    7, 15,  8,  5,  4, 22, 24,  8, 17, 18, 21, 20, 23, 11, 26, 16,
/* 3x */    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5, 19, 12, 14, 13,  6,
/* 4x */    5,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
/* 5x */    1,  1,  1,  1,  1,  1,  1,  1,  0,  2,  2,  9, 28, 28, 28,  2,
/* 6x */    8,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
/* 7x */    1,  1,  1,  1,  1,  1,  1,  1,  0,  2,  2, 28, 10, 28, 25, 28,
/* 8x */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* 9x */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Ax */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Bx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Cx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Dx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Ex */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 30,
/* Fx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
];

/*
** The charMap() macro maps alphabetic characters (only) into their
** lower-case ASCII equivalent.  On ASCII machines, this is just
** an upper-to-lower case map.  On EBCDIC machines we also need
** to adjust the encoding.  The mapping is only valid for alphabetics
** which are the only characters for which this feature is used.
**
** Used by keywordhash.h
*/
fn charMap(x: u8) -> u8 {
    x.to_ascii_lowercase()
}

/*
** The sqlite3KeywordCode function looks up an identifier to determine if
** it is a keyword.  If it is a keyword, the token code of that keyword is
** returned.  If the input is not a keyword, TK_ID is returned.
**
** The implementation of this routine was generated by a program,
** mkkeywordhash.c, located in the tool subdirectory of the distribution.
** The output of the mkkeywordhash.c program is written into a file
** named keywordhash.h and then included into this source file by
** the #include below.
*/
// #include "keywordhash.h"

#[expect(non_camel_case_types)]
#[derive(PartialEq)]
enum Token {
    TK_BITAND,
    TK_BITNOT,
    TK_BITOR,
    TK_BLOB,
    TK_COMMA,
    TK_COMMENT,
    TK_CONCAT,
    TK_DOT,
    TK_EQ,
    TK_FLOAT,
    TK_GE,
    TK_GT,
    TK_ID,
    TK_ILLEGAL,
    TK_INTEGER,
    TK_JOIN_KW,
    TK_LE,
    TK_LP,
    TK_LSHIFT,
    TK_LT,
    TK_MINUS,
    TK_NE,
    TK_OVER,
    TK_PLUS,
    TK_PTR,
    TK_QNUMBER,
    TK_REM,
    TK_RP,
    TK_RSHIFT,
    TK_SEMI,
    TK_SLASH,
    TK_SPACE,
    TK_STAR,
    TK_STRING,
    TK_VARIABLE,
    TK_WINDOW,
}
use Token::*;

const SQLITE_DIGIT_SEPARATOR: u8 = b'_';

fn sqlite3Isxdigit(byte: u8) -> bool {
    byte.is_ascii_hexdigit()
}

fn sqlite3Isdigit(byte: u8) -> bool {
    byte.is_ascii_digit()
}

/*
** If X is a character that can be used in an identifier then
** IdChar(X) will be true.  Otherwise it is false.
**
** For ASCII, any character with the high-order bit set is
** allowed in an identifier.  For 7-bit characters,
** sqlite3IsIdChar[X] must be 1.
**
** For EBCDIC, the rules are more complex but have the same
** end result.
**
** Ticket #1066.  the SQL standard does not allow '$' in the
** middle of identifiers.  But many SQL implementations do.
** SQLite will allow '$' in identifiers for compatibility.
** But the feature is undocumented.
*/
fn IdChar(c: u8) -> bool {
    c.is_ascii_alphanumeric() || !c.is_ascii()
}

/*
** Return the id of the next token in string (*pz). Before returning, set
** (*pz) to point to the byte following the parsed token.
*/
fn getToken(pz: &mut &[u8]) -> Token {
    let mut t: Token;
    let mut z = *pz;
    loop {
        let (new_id, new_t) = sqlite3GetToken(z);
        z = &z[..new_id];
        t = new_t;
        if !(t == TK_SPACE || t == TK_COMMENT) {
            break;
        }
    }
    if (t == TK_ID || t == TK_STRING || t == TK_JOIN_KW || t == TK_WINDOW || t == TK_OVER) {
        t = TK_ID;
    }
    *pz = z;
    return t;
}

fn sqlite3Isspace(c: u8) -> bool {
    c.is_ascii_whitespace()
}

/*
** Return the length (in bytes) of the token that begins at z[0].
** Store the token type in *tokenType before returning.
*/
// z must be 0 terminated
fn sqlite3GetToken(z: &[u8]) -> (usize, Token) {
    let tokenType;
    let i;
    match aiClass[z[0] as usize] {
        /* Switch on the character-class of the first byte
         ** of the token. See the comment on the CC_ defines
         ** above. */
        CC_SPACE => {
            i = 1;
            while z[i].is_ascii_whitespace() {
                i += 1;
            }
            tokenType = TK_SPACE;
            return (i, tokenType);
        }
        CC_MINUS => {
            if z[1] == b'-' {
                i = 2;
                while z[i] != 0 && z[i] != b'\n' {
                    i += 1
                }
                tokenType = TK_COMMENT;
                return (i, tokenType);
            } else if (z[1] == b'>') {
                tokenType = TK_PTR;
                return (2 + (z[2] == b'>') as usize, tokenType);
            }
            tokenType = TK_MINUS;
            return (1, tokenType);
        }
        CC_LP => {
            tokenType = TK_LP;
            return (1, tokenType);
        }
        CC_RP => {
            tokenType = TK_RP;
            return (1, tokenType);
        }
        CC_SEMI => {
            tokenType = TK_SEMI;
            return (1, tokenType);
        }
        CC_PLUS => {
            tokenType = TK_PLUS;
            return (1, tokenType);
        }
        CC_STAR => {
            tokenType = TK_STAR;
            return (1, tokenType);
        }
        CC_SLASH => {
            if (z[1] != b'*' || z[2] == 0) {
                tokenType = TK_SLASH;
                return (1, tokenType);
            }
            i = 3;
            let mut c = z[2];
            while (c != b'*' || z[i] != b'/') && {
                c = z[i];
                c != 0
            } {
                i += 1;
            }
            if (c != 0) {
                i += 1
            };
            tokenType = TK_COMMENT;
            return (i, tokenType);
        }
        CC_PERCENT => {
            tokenType = TK_REM;
            return (1, tokenType);
        }
        CC_EQ => {
            tokenType = TK_EQ;
            return (1 + (z[1] == b'=') as usize, tokenType);
        }
        CC_LT => {
            let c = z[1];
            if (c == b'=') {
                tokenType = TK_LE;
                return (2, tokenType);
            } else if (c == b'>') {
                tokenType = TK_NE;
                return (2, tokenType);
            } else if (c == b'<') {
                tokenType = TK_LSHIFT;
                return (2, tokenType);
            } else {
                tokenType = TK_LT;
                return (1, tokenType);
            }
        }
        CC_GT => {
            let c = z[1];
            if (c == b'=') {
                tokenType = TK_GE;
                return (2, tokenType);
            } else if (c == b'>') {
                tokenType = TK_RSHIFT;
                return (2, tokenType);
            } else {
                tokenType = TK_GT;
                return (1, tokenType);
            }
        }
        CC_BANG => {
            if (z[1] != b'=') {
                tokenType = TK_ILLEGAL;
                return (1, tokenType);
            } else {
                tokenType = TK_NE;
                return (2, tokenType);
            }
        }
        CC_PIPE => {
            if (z[1] != b'|') {
                tokenType = TK_BITOR;
                return (1, tokenType);
            } else {
                tokenType = TK_CONCAT;
                return (2, tokenType);
            }
        }
        CC_COMMA => {
            tokenType = TK_COMMA;
            return (1, tokenType);
        }
        CC_AND => {
            tokenType = TK_BITAND;
            return (1, tokenType);
        }
        CC_TILDA => {
            tokenType = TK_BITNOT;
            return (1, tokenType);
        }
        CC_QUOTE => {
            let delim = z[0];
            i = 1;
            let mut c = z[i];
            while c != 0 {
                if (c == delim) {
                    if (z[i + 1] == delim) {
                        i += 1;
                    } else {
                        break;
                    }
                }

                i += 1;
                c = z[i];
            }
            if (c == b'\'') {
                tokenType = TK_STRING;
                return (i + 1, tokenType);
            } else if (c != 0) {
                tokenType = TK_ID;
                return (i + 1, tokenType);
            } else {
                tokenType = TK_ILLEGAL;
                return (i, tokenType);
            }
        }
        CC_DOT => {
            if (!sqlite3Isdigit(z[1])) {
                tokenType = TK_DOT;
                return (1, tokenType);
            }
            /* If the next character is a digit, this is a floating point
             ** number that begins with ".".  Fall thru into the next case */
            // /* no break */ deliberate_fall_through
        }
        CC_DIGIT => {
            tokenType = TK_INTEGER;
            if (z[0] == b'0' && (z[1] == b'x' || z[1] == b'X') && sqlite3Isxdigit(z[2])) {
                i = 3;
                loop {
                    if (!sqlite3Isxdigit(z[i])) {
                        if (z[i] == SQLITE_DIGIT_SEPARATOR) {
                            tokenType = TK_QNUMBER;
                        } else {
                            break;
                        }
                    }
                    i += 1;
                }
            } else {
                i = 0;
                loop {
                    if (!sqlite3Isdigit(z[i])) {
                        if (z[i] == SQLITE_DIGIT_SEPARATOR) {
                            tokenType = TK_QNUMBER;
                        } else {
                            break;
                        }
                    }
                    i += 1;
                }
                if (z[i] == b'.') {
                    if (tokenType == TK_INTEGER) {
                        tokenType = TK_FLOAT
                    };
                    i += 1;
                    loop {
                        if (!sqlite3Isdigit(z[i])) {
                            if (z[i] == SQLITE_DIGIT_SEPARATOR) {
                                tokenType = TK_QNUMBER;
                            } else {
                                break;
                            }
                        }
                        i += 1;
                    }
                }
                if ((z[i] == b'e' || z[i] == b'E')
                    && (sqlite3Isdigit(z[i + 1])
                        || ((z[i + 1] == b'+' || z[i + 1] == b'-') && sqlite3Isdigit(z[i + 2]))))
                {
                    if (tokenType == TK_INTEGER) {
                        tokenType = TK_FLOAT
                    };
                    i += 2;
                    loop {
                        if (!sqlite3Isdigit(z[i])) {
                            if (z[i] == SQLITE_DIGIT_SEPARATOR) {
                                tokenType = TK_QNUMBER;
                            } else {
                                break;
                            }
                        }
                        i += 1
                    }
                }
            }
            while (IdChar(z[i])) {
                tokenType = TK_ILLEGAL;
                i += 1;
            }
            return (i, tokenType);
        }
        CC_QUOTE2 => {
            i = 1;
            let mut c = z[0];
            while c != b']' && {
                c = z[i];
                c != 0
            } {
                i += 1
            }
            tokenType = if c == b']' { TK_ID } else { TK_ILLEGAL };
            return (i, tokenType);
        }
        CC_VARNUM => {
            tokenType = TK_VARIABLE;
            i = 1;
            while sqlite3Isdigit(z[i]) {
                i += 1
            }
            return (i, tokenType);
        }
        CC_DOLLAR | CC_VARALPHA => {
            let mut n = 0i64;
            tokenType = TK_VARIABLE;
            i = 1;
            let mut c;
            while {
                c = z[i];
                c != 0
            } {
                if (IdChar(c)) {
                    n += 1;
                } else if (c == b'(' && n > 0) {
                    i += 1;
                    while {
                        c = z[i];
                        c != 0
                    } && !sqlite3Isspace(c)
                        && c != b')'
                    {
                        i += 1;
                    }
                    if (c == b')') {
                        i += 1;
                    } else {
                        tokenType = TK_ILLEGAL;
                    }
                    break;
                } else if (c == b':' && z[i + 1] == b':') {
                    i += 1;
                } else {
                    break;
                }
                i += 1;
            }
            if (n == 0) {
                tokenType = TK_ILLEGAL
            };
            return (i, tokenType);
        }
        CC_KYWD0 => {
            if (aiClass[z[1] as usize] > CC_KYWD) {
                i = 1;
            } else {
                i = 2;
                while aiClass[z[i] as usize] <= CC_KYWD {
                    i += 1
                }
                if (IdChar(z[i])) {
                    /* This token started out using characters that can appear in keywords,
                     ** but z[i] is a character not allowed within keywords, so this must
                     ** be an identifier instead */
                    i += 1;
                } else {
                    tokenType = TK_ID;
                    return (keywordCode(z, i, tokenType), tokenType);
                }
            }
        }
        CC_X => {
            if z[1] == b'\'' {
                tokenType = TK_BLOB;
                let mut i = 2;
                while sqlite3Isxdigit(z[i]) {
                    i += 1
                }
                if (z[i] != b'\'' || i % 2 != 0) {
                    tokenType = TK_ILLEGAL;
                    while (z[i] != 0 && z[i] != b'\'') {
                        i += 1;
                    }
                }
                if (z[i] != 0) {
                    i += 1
                };
                return (i, tokenType);
            }
            i = 1;
        }
        CC_KYWD | CC_ID => {
            i = 1;
        }
        CC_BOM => {
            if z[1] == 0xbb && z[2] == 0xbf {
                tokenType = TK_SPACE;
                return (3, tokenType);
            }
            i = 1;
        }
        CC_NUL => {
            tokenType = TK_ILLEGAL;
            return (0, tokenType);
        }
        _ => {
            tokenType = TK_ILLEGAL;
            return (1, tokenType);
        }
    }
    while (IdChar(z[i])) {
        i += 1;
    }
    tokenType = TK_ID;
    return (i, tokenType);
}
