/* Character classes for tokenizing
**
** In the sqlite3GetToken() function, a switch() on aiClass[c] is implemented
** using a lookup table, whereas a switch() directly on c uses a binary search.
** The lookup table is much faster.  To maximize speed, and to ensure that
** a lookup table is used, all of the classes need to be small integers and
** all of them need to be used within the switch.
*/
const CC_X: u8 = 0; /* The letter 'x', or start of BLOB literal */
const CC_KYWD0: u8 = 1; /* First letter of a keyword */
const CC_KYWD: u8 = 2; /* Alphabetics or '_'.  Usable in a keyword */
const CC_DIGIT: u8 = 3; /* Digits */
const CC_DOLLAR: u8 = 4; /* '$' */
const CC_VARALPHA: u8 = 5; /* '@', '#', ':'.  Alphabetic SQL variables */
const CC_VARNUM: u8 = 6; /* '?'.  Numeric SQL variables */
const CC_SPACE: u8 = 7; /* Space characters */
const CC_QUOTE: u8 = 8; /* '"', '\'', or '`'.  String literals, quoted ids */
const CC_QUOTE2: u8 = 9; /* '['.   [...] style quoted ids */
const CC_PIPE: u8 = 10; /* '|'.   Bitwise OR or concatenate */
const CC_MINUS: u8 = 11; /* '-'.  Minus or SQL-style comment */
const CC_LT: u8 = 12; /* '<'.  Part of < or <= or <> */
const CC_GT: u8 = 13; /* '>'.  Part of > or >= */
const CC_EQ: u8 = 14; /* '='.  Part of = or == */
const CC_BANG: u8 = 15; /* '!'.  Part of != */
const CC_SLASH: u8 = 16; /* '/'.  / or c-style comment */
const CC_LP: u8 = 17; /* '(' */
const CC_RP: u8 = 18; /* ')' */
const CC_SEMI: u8 = 19; /* ';' */
const CC_PLUS: u8 = 20; /* '+' */
const CC_STAR: u8 = 21; /* '*' */
const CC_PERCENT: u8 = 22; /* '%' */
const CC_COMMA: u8 = 23; /* ',' */
const CC_AND: u8 = 24; /* '&' */
const CC_TILDA: u8 = 25; /* '~' */
const CC_DOT: u8 = 26; /* '.' */
const CC_ID: u8 = 27; /* unicode characters usable in IDs */
const CC_ILLEGAL: u8 = 28; /* Illegal character */
const CC_NUL: u8 = 29; /* 0x00 */
const CC_BOM: u8 = 30; /* First byte of UTF8 BOM:  0xEF 0xBB 0xBF */

#[rustfmt::skip]
static  aiClass: &[u8] = &[
/*         x0  x1  x2  x3  x4  x5  x6  x7  x8  x9  xa  xb  xc  xd  xe  xf */
/* 0x */   29, 28, 28, 28, 28, 28, 28, 28, 28,  7,  7, 28,  7,  7, 28, 28,
/* 1x */   28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
/* 2x */    7, 15,  8,  5,  4, 22, 24,  8, 17, 18, 21, 20, 23, 11, 26, 16,
/* 3x */    3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5, 19, 12, 14, 13,  6,
/* 4x */    5,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
/* 5x */    1,  1,  1,  1,  1,  1,  1,  1,  0,  2,  2,  9, 28, 28, 28,  2,
/* 6x */    8,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
/* 7x */    1,  1,  1,  1,  1,  1,  1,  1,  0,  2,  2, 28, 10, 28, 25, 28,
/* 8x */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* 9x */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Ax */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Bx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Cx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Dx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
/* Ex */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 30,
/* Fx */   27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
];

/*
** The charMap() macro maps alphabetic characters (only) into their
** lower-case ASCII equivalent.  On ASCII machines, this is just
** an upper-to-lower case map.  On EBCDIC machines we also need
** to adjust the encoding.  The mapping is only valid for alphabetics
** which are the only characters for which this feature is used.
**
** Used by keywordhash.h
*/
fn charMap(x: u8) -> u8 {
    x.to_ascii_lowercase()
}

/*
** The sqlite3KeywordCode function looks up an identifier to determine if
** it is a keyword.  If it is a keyword, the token code of that keyword is
** returned.  If the input is not a keyword, TK_ID is returned.
**
** The implementation of this routine was generated by a program,
** mkkeywordhash.c, located in the tool subdirectory of the distribution.
** The output of the mkkeywordhash.c program is written into a file
** named keywordhash.h and then included into this source file by
** the #include below.
*/
// #include "keywordhash.h"

#[expect(non_camel_case_types)]
#[derive(PartialEq)]
enum Token {
    TK_BITAND,
    TK_BITNOT,
    TK_BITOR,
    TK_BLOB,
    TK_COMMA,
    TK_COMMENT,
    TK_CONCAT,
    TK_DOT,
    TK_EQ,
    TK_FLOAT,
    TK_GE,
    TK_GT,
    TK_ID,
    TK_ILLEGAL,
    TK_INTEGER,
    TK_JOIN_KW,
    TK_LE,
    TK_LP,
    TK_LSHIFT,
    TK_LT,
    TK_MINUS,
    TK_NE,
    TK_OVER,
    TK_PLUS,
    TK_PTR,
    TK_QNUMBER,
    TK_REM,
    TK_RP,
    TK_RSHIFT,
    TK_SEMI,
    TK_SLASH,
    TK_SPACE,
    TK_STAR,
    TK_STRING,
    TK_VARIABLE,
    TK_WINDOW,
}
use Token::*;

const SQLITE_DIGIT_SEPARATOR: u8 = b'_';

fn sqlite3Isxdigit(byte: u8) -> bool {
    byte.is_ascii_hexdigit()
}

fn sqlite3Isdigit(byte: u8) -> bool {
    byte.is_ascii_digit()
}

/*
** If X is a character that can be used in an identifier then
** IdChar(X) will be true.  Otherwise it is false.
**
** For ASCII, any character with the high-order bit set is
** allowed in an identifier.  For 7-bit characters,
** sqlite3IsIdChar[X] must be 1.
**
** For EBCDIC, the rules are more complex but have the same
** end result.
**
** Ticket #1066.  the SQL standard does not allow '$' in the
** middle of identifiers.  But many SQL implementations do.
** SQLite will allow '$' in identifiers for compatibility.
** But the feature is undocumented.
*/
fn IdChar(c: u8) -> bool {
    c.is_ascii_alphanumeric() || !c.is_ascii()
}

/*
** Return the id of the next token in string (*pz). Before returning, set
** (*pz) to point to the byte following the parsed token.
*/
fn getToken(pz: &mut &[u8]) -> Token {
    let mut t: Token;
    let mut z = *pz;
    loop {
        let (new_id, new_t) = sqlite3GetToken(z);
        z = &z[..new_id];
        t = new_t;
        if !(t == TK_SPACE || t == TK_COMMENT) {
            break;
        }
    }
    if t == TK_ID || t == TK_STRING || t == TK_JOIN_KW || t == TK_WINDOW || t == TK_OVER {
        t = TK_ID;
    }
    *pz = z;
    return t;
}

fn sqlite3Isspace(c: u8) -> bool {
    c.is_ascii_whitespace()
}

/*
** Return the length (in bytes) of the token that begins at z[0].
** Store the token type in *tokenType before returning.
*/
// z must be 0 terminated
fn sqlite3GetToken(z0: ZeroTerminated) -> (usize, Token) {
    let Some((v, mut z)) = z0.next() else {
        return (z0.1, TK_ILLEGAL);
    };

    let tokenType;
    let i;
    match aiClass[v as usize] {
        /* Switch on the character-class of the first byte
         ** of the token. See the comment on the CC_ defines
         ** above. */
        CC_SPACE => {
            z.take_while(|v| v.is_ascii_whitespace());
            return (z.1, TK_SPACE);
        }
        CC_MINUS => match z.next() {
            Some((b'-', z)) => {
                z.take_while(|v| v != b'\n');
                return (z.1, TK_COMMENT);
            }
            Some((b'>', mut z)) => {
                z.take_if(|v| v == b'>');
                return (z.1, TK_PTR);
            }
            _ => return (z.1, TK_MINUS),
        },
        CC_LP => return (z.1, TK_LP),
        CC_RP => return (z.1, TK_RP),
        CC_SEMI => return (z.1, TK_SEMI),
        CC_PLUS => return (z.1, TK_PLUS),
        CC_STAR => return (z.1, TK_STAR),
        CC_SLASH => {
            if let Some((b'*', z)) = z.next()
                && let Some((mut prev, mut z)) = z.next()
            {
                z.take_until_and_including(|v| {
                    let found = prev == b'*' && v == b'/';
                    prev = v;
                    found
                });
                return (z.1, TK_COMMENT);
            } else {
                return (z.1, TK_SLASH);
            }
        }
        CC_PERCENT => return (z.1, TK_REM),
        CC_EQ => {
            z.take_if(|v| v == b'=');
            return (z.1, TK_EQ);
        }
        CC_LT => match z.next() {
            Some((b'=', z)) => return (z.1, TK_LE),
            Some((b'>', z)) => return (z.1, TK_NE),
            Some((b'<', z)) => return (z.1, TK_LSHIFT),
            _ => return (z.1, TK_LT),
        },
        CC_GT => match z.next() {
            Some((b'=', z)) => return (z.1, TK_GE),
            Some((b'>', z)) => return (z.1, TK_RSHIFT),
            _ => return (z.1, TK_GT),
        },
        CC_BANG => match z.next() {
            Some((b'=', z)) => return (z.1, TK_NE),
            _ => return (z.1, TK_ILLEGAL),
        },
        CC_PIPE => match z.next() {
            Some((b'|', z)) => return (z.1, TK_CONCAT),
            _ => return (z.1, TK_BITOR),
        },
        CC_COMMA => return (z.1, TK_COMMA),
        CC_AND => return (z.1, TK_BITAND),
        CC_TILDA => return (z.1, TK_BITNOT),
        delim @ CC_QUOTE => {
            loop {
                let Some(_) = z.take_until_and_including(|x| x == delim) else {
                    return (z.1, TK_ILLEGAL);
                };
                if let Some((v, new)) = z.next()
                    && v == delim
                {
                    z = new;
                } else {
                    break;
                }
            }
            if delim == b'\'' {
                return (z.1, TK_STRING);
            } else {
                return (z.1, TK_ID);
            }
        }
        first @ (CC_DOT | CC_DIGIT) => {
            if first == CC_DOT && !z.peek(sqlite3Isdigit) {
                return (z.1, TK_DOT);
            }

            tokenType = TK_INTEGER;
            macro_rules! assign {
                ($typ:expr) => {{
                    tokenType = $typ;
                    true
                }};
            }

            if first == b'0'
                && let Some((b'x' | b'X', new)) = z.next()
                && let Some((v, new)) = new.next()
                && sqlite3Isxdigit(v)
            {
                z = new;
                z.take_while(|v| {
                    sqlite3Isxdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                });
            } else {
                z = z0; // reset to before the first character
                z.take_while(|v| {
                    sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                });
                if let Some((b'.', new)) = z.next() {
                    z = new;
                    if tokenType == TK_INTEGER {
                        tokenType = TK_FLOAT
                    };
                    z.take_while(|v| {
                        sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                    });
                }
                if let Some((b'e' | b'E', new)) = z.next()
                    && let Some((v, new)) = new.next()
                    && (sqlite3Isdigit(v) || ((v == b'+' || v == b'-') && new.peek(sqlite3Isdigit)))
                {
                    z = new;
                    if tokenType == TK_INTEGER {
                        tokenType = TK_FLOAT
                    };
                    z.take_while(|v| {
                        sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                    });
                }
            }
            z.take_while(|v| IdChar(v) && assign!(TK_ILLEGAL));
            return (z.1, tokenType);
        }
        CC_QUOTE2 => {
            let found = z.take_until_and_including(|v| v == b']').is_some();
            tokenType = if found { TK_ID } else { TK_ILLEGAL };
            return (z.1, tokenType);
        }
        CC_VARNUM => {
            z.take_while(sqlite3Isdigit);
            return (z.1, TK_VARIABLE);
        }
        CC_DOLLAR | CC_VARALPHA => {
            let mut n = 0i64;
            tokenType = TK_VARIABLE;
            while let Some((c, mut new)) = z.next() {
                if IdChar(c) {
                    z = new;
                    n += 1;
                } else if c == b'(' && n > 0 {
                    z = new;
                    z.take_while(|v| !sqlite3Isspace(c) && c != b')');
                    if let Some((b')', new)) = z.next() {
                        z = new;
                    } else {
                        tokenType = TK_ILLEGAL
                    }
                    break;
                } else if c == b':'
                    && let Some((b':', new)) = new.next()
                {
                    z = new;
                } else {
                    break;
                }
            }

            if n == 0 {
                tokenType = TK_ILLEGAL
            };
            return (i, tokenType);
        }
        CC_X => {
            if z[1] == b'\'' {
                tokenType = TK_BLOB;
                let mut i = 2;
                while sqlite3Isxdigit(z[i]) {
                    i += 1
                }
                if z[i] != b'\'' || i % 2 != 0 {
                    tokenType = TK_ILLEGAL;
                    while z[i] != 0 && z[i] != b'\'' {
                        i += 1;
                    }
                }
                if z[i] != 0 {
                    i += 1
                };
                return (i, tokenType);
            }
            i = 1;
        }
        CC_KYWD0 | CC_KYWD | CC_ID => {
            i = 1;
        }
        CC_BOM => {
            if let Some((0xbb, new)) = z.next()
                && let Some((0xbf, new)) = new.next()
            {
                z = new;
                return (z.1, TK_SPACE);
            }
            i = 1;
        }
        CC_NUL => {}
        _ => {
            tokenType = TK_ILLEGAL;
            return (1, tokenType);
        }
    }
    while IdChar(z[i]) {
        i += 1;
    }
    tokenType = TK_ID;
    return (i, tokenType);
}

struct ZeroTerminated<'x>(&'x [u8], pub usize);

impl<'x> ZeroTerminated<'x> {
    fn new(slice: &'x [u8]) -> Self {
        assert!(slice[slice.len() - 1] == 0);
        Self(slice, 0)
    }

    fn next(&self) -> Option<(u8, Self)> {
        let v = unsafe { *self.0.get_unchecked(self.1) };
        if v == 0 {
            return None;
        }
        Some((v, Self(self.0, self.1 + 1)))
    }

    fn next_if(&self, f: impl FnOnce(u8) -> bool) -> Option<Self> {
        self.next().and_then(|(v, new)| f(v).then_some(new))
    }

    fn take_while(&mut self, f: impl Fn(u8) -> bool) {
        while let Some((v, new)) = self.next()
            && f(v)
        {
            *self = new;
        }
    }

    fn take_until_and_including(&mut self, f: impl Fn(u8) -> bool) -> Option<u8> {
        loop {
            let (v, new) = self.next()?;
            *self = new;
            if f(v) {
                return Some(v);
            }
        }
    }

    fn take_if(&mut self, f: impl FnOnce(u8) -> bool) {
        if let Some((v, new)) = self.next()
            && f(v)
        {
            *self = new;
        }
    }

    fn peek(&self, f: impl FnOnce(u8) -> bool) -> bool {
        if let Some((v, _)) = self.next()
            && f(v)
        {
            true
        } else {
            false
        }
    }
}
