/*
** The sqlite3KeywordCode function looks up an identifier to determine if
** it is a keyword.  If it is a keyword, the token code of that keyword is
** returned.  If the input is not a keyword, TK_ID is returned.
**
** The implementation of this routine was generated by a program,
** mkkeywordhash.c, located in the tool subdirectory of the distribution.
** The output of the mkkeywordhash.c program is written into a file
** named keywordhash.h and then included into this source file by
** the #include below.
*/
// #include "keywordhash.h"

#[expect(non_camel_case_types)]
#[derive(PartialEq)]
enum Token {
    TK_BITAND,
    TK_BITNOT,
    TK_BITOR,
    TK_BLOB,
    TK_COMMA,
    TK_COMMENT,
    TK_CONCAT,
    TK_DOT,
    TK_EQ,
    TK_FLOAT,
    TK_GE,
    TK_GT,
    TK_ID,
    TK_ILLEGAL,
    TK_INTEGER,
    TK_JOIN_KW,
    TK_LE,
    TK_LP,
    TK_LSHIFT,
    TK_LT,
    TK_MINUS,
    TK_NE,
    TK_OVER,
    TK_PLUS,
    TK_PTR,
    TK_QNUMBER,
    TK_REM,
    TK_RP,
    TK_RSHIFT,
    TK_SEMI,
    TK_SLASH,
    TK_SPACE,
    TK_STAR,
    TK_STRING,
    TK_VARIABLE,
    TK_WINDOW,
}

use Token::*;

const SQLITE_DIGIT_SEPARATOR: u8 = b'_';

fn sqlite3Isxdigit(byte: u8) -> bool {
    byte.is_ascii_hexdigit()
}

fn sqlite3Isdigit(byte: u8) -> bool {
    byte.is_ascii_digit()
}

fn sqlite3Isspace(c: u8) -> bool {
    c.is_ascii_whitespace()
}

/*
** If X is a character that can be used in an identifier then
** IdChar(X) will be true.  Otherwise it is false.
**
** For ASCII, any character with the high-order bit set is
** allowed in an identifier.  For 7-bit characters,
** sqlite3IsIdChar[X] must be 1.
**
** For EBCDIC, the rules are more complex but have the same
** end result.
**
** Ticket #1066.  the SQL standard does not allow '$' in the
** middle of identifiers.  But many SQL implementations do.
** SQLite will allow '$' in identifiers for compatibility.
** But the feature is undocumented.
*/
fn IdChar(c: u8) -> bool {
    c.is_ascii_alphanumeric() || !c.is_ascii()
}

/*
** Return the id of the next token in string (*pz). Before returning, set
** (*pz) to point to the byte following the parsed token.
*/
fn getToken(pz: &mut &[u8]) -> Token {
    let mut t: Token;
    let mut z = *pz;
    loop {
        let (new_z, new_t) = sqlite3GetToken(ZeroTerminated::new(z));
        z = &z[new_z.1..];
        t = new_t;
        if !(t == TK_SPACE || t == TK_COMMENT) {
            break;
        }
    }
    if t == TK_ID || t == TK_STRING || t == TK_JOIN_KW || t == TK_WINDOW || t == TK_OVER {
        t = TK_ID;
    }
    *pz = z;
    return t;
}

/*
** Return the length (in bytes) of the token that begins at z[0].
** Store the token type in *tokenType before returning.
*/
fn sqlite3GetToken(z0: ZeroTerminated) -> (ZeroTerminated, Token) {
    let Some((v, mut z)) = z0.next() else {
        return (z0, TK_ILLEGAL);
    };
    if sqlite3Isspace(v) {
        z.take_while(sqlite3Isspace);
        return (z, TK_SPACE);
    }

    let token = match v {
        b'-' => match z.next() {
            Some((b'-', new)) => {
                z = new;
                z.take_while(|v| v != b'\n');
                TK_COMMENT
            }
            Some((b'>', new)) => {
                z = new;
                z.take_if(|v| v == b'>');
                TK_PTR
            }
            _ => TK_MINUS,
        },
        b'(' => TK_LP,
        b')' => TK_RP,
        b';' => TK_SEMI,
        b'+' => TK_PLUS,
        b'*' => TK_STAR,
        b'/' => {
            if let Some((b'*', new)) = z.next()
                && let Some((mut prev, new)) = new.next()
            {
                z = new;
                z.take_until_and_including(|v| {
                    let found = prev == b'*' && v == b'/';
                    prev = v;
                    found
                });
                TK_COMMENT
            } else {
                TK_SLASH
            }
        }
        b'%' => TK_REM,
        b'=' => {
            z.take_if(|v| v == b'=');
            TK_EQ
        }
        b'<' => match z.next() {
            Some((b'=', new)) => return (new, TK_LE),
            Some((b'>', new)) => return (new, TK_NE),
            Some((b'<', new)) => return (new, TK_LSHIFT),
            _ => TK_LT,
        },
        b'>' => match z.next() {
            Some((b'=', new)) => return (new, TK_GE),
            Some((b'>', new)) => return (new, TK_RSHIFT),
            _ => TK_GT,
        },
        b'!' => match z.next() {
            Some((b'=', new)) => return (new, TK_NE),
            _ => TK_ILLEGAL,
        },
        b'|' => match z.next() {
            Some((b'|', new)) => return (new, TK_CONCAT),
            _ => TK_BITOR,
        },
        b',' => TK_COMMA,
        b'&' => TK_BITAND,
        b'~' => TK_BITNOT,
        delim @ (b'\'' | b'"' | b'`') => {
            loop {
                let true = z.take_until_and_including(|x| x == delim) else {
                    return (z, TK_ILLEGAL);
                };
                if let Some((v, new)) = z.next()
                    && v == delim
                {
                    z = new;
                } else {
                    break;
                }
            }
            if delim == b'\'' { TK_STRING } else { TK_ID }
        }
        b'.' if !z.peek(sqlite3Isdigit) => TK_DOT,
        first @ (b'.' | b'0'..=b'9') => {
            let mut token = TK_INTEGER;
            macro_rules! assign {
                ($typ:expr) => {{
                    token = $typ;
                    true
                }};
            }

            if first == b'0'
                && let Some((b'x' | b'X', new)) = z.next()
                && let Some((v, new)) = new.next()
                && sqlite3Isxdigit(v)
            {
                z = new;
                z.take_while(|v| {
                    sqlite3Isxdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                });
            } else {
                z = z0; // reset to before the first character
                z.take_while(|v| {
                    sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                });
                if let Some((b'.', new)) = z.next() {
                    z = new;
                    if token == TK_INTEGER {
                        token = TK_FLOAT
                    };
                    z.take_while(|v| {
                        sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                    });
                }
                if let Some((b'e' | b'E', new)) = z.next()
                    && let Some((v, new)) = new.next()
                    && (sqlite3Isdigit(v) || ((v == b'+' || v == b'-') && new.peek(sqlite3Isdigit)))
                {
                    z = new;
                    if token == TK_INTEGER {
                        token = TK_FLOAT
                    };
                    z.take_while(|v| {
                        sqlite3Isdigit(v) || v == SQLITE_DIGIT_SEPARATOR && assign!(TK_QNUMBER)
                    });
                }
            }
            z.take_while(|v| IdChar(v) && assign!(TK_ILLEGAL));
            token
        }
        b'[' => {
            let found = z.take_until_and_including(|v| v == b']');
            if found { TK_ID } else { TK_ILLEGAL }
        }
        b'?' => {
            z.take_while(sqlite3Isdigit);
            TK_VARIABLE
        }
        b'$' | b'@' | b'#' | b':' => {
            let mut n = 0i64;
            loop {
                match z.next() {
                    Some((c, new)) if IdChar(c) => {
                        z = new;
                        n += 1;
                    }
                    Some((b'(', new)) if n > 0 => {
                        z = new;
                        z.take_while(|v| !sqlite3Isspace(v) && v != b')');
                        if let Some((b')', new)) = z.next() {
                            z = new;
                        } else {
                            return (z, TK_ILLEGAL);
                        }
                        break;
                    }
                    Some((b':', new)) if let Some((b':', new)) = new.next() => {
                        z = new;
                    }
                    _ => break,
                }
            }
            if n == 0 { TK_ILLEGAL } else { TK_VARIABLE }
        }
        b'x' if let Some((b'\'', new)) = z.next() => {
            z = new;
            let count = z.take_while(sqlite3Isxdigit);
            if let Some((b'\'', new)) = z.next()
                && count % 2 == 0
            {
                z = new;
                TK_BLOB
            } else {
                z.take_until_and_including(|v| v == b'\'');
                TK_ILLEGAL
            }
        }
        0xef if let Some((0xbb, new)) = z.next()
            && let Some((0xbf, new)) = new.next() =>
        {
            z = new;
            TK_SPACE
        }
        v if IdChar(v) => {
            z.take_while(IdChar);
            TK_ID
        }
        _ => TK_ILLEGAL,
    };
    (z, token)
}

struct ZeroTerminated<'x>(&'x [u8], pub usize);

impl<'x> ZeroTerminated<'x> {
    fn new(slice: &'x [u8]) -> Self {
        assert!(slice[slice.len() - 1] == 0);
        Self(slice, 0)
    }

    fn next(&self) -> Option<(u8, Self)> {
        let v = unsafe { *self.0.get_unchecked(self.1) };
        if v == 0 {
            return None;
        }
        Some((v, Self(self.0, self.1 + 1)))
    }

    fn take_while(&mut self, mut f: impl FnMut(u8) -> bool) -> usize {
        let mut count = 0;
        while let Some((v, new)) = self.next()
            && f(v)
        {
            *self = new;
            count += 1;
        }
        count
    }

    fn take_until_and_including(&mut self, mut f: impl FnMut(u8) -> bool) -> bool {
        loop {
            let Some((v, new)) = self.next() else {
                return false;
            };
            *self = new;
            if f(v) {
                return true;
            }
        }
    }

    fn take_if(&mut self, f: impl FnOnce(u8) -> bool) {
        if let Some((v, new)) = self.next()
            && f(v)
        {
            *self = new;
        }
    }

    fn peek(&self, f: impl FnOnce(u8) -> bool) -> bool {
        if let Some((v, _)) = self.next()
            && f(v)
        {
            true
        } else {
            false
        }
    }
}
